version: "3.9"
services:
  customers:
    container_name: customers
    restart: always
    build: ./customers
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  orders:
    container_name: orders
    restart: always
    build: ./orders
    ports:
      - "4001:4001"
    depends_on:
      - mongo
  payments:
    container_name: payments
    restart: always
    build: ./payments
    ports:
      - "4002:4002"
    depends_on:
      - mongo
  products:
    container_name: products
    restart: always
    build: ./products
    ports:
      - "4003:4003"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27018"
    volumes:
      - ./data:/data/db
    ports:
       - "27018:27018"   
